name: Continuous Preview Release

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - dev

jobs:
  publish_preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build:prod

      - name: Publish to pkg.pr.new
        run: npx pkg-pr-new publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}